"""
AI Keywords and Tech Stack Keywords for Pipeline 2
app/pipelines/keywords.py
"""

from __future__ import annotations

# AI-related keywords for job posting classification
AI_KEYWORDS = frozenset([
    # Core AI / ML terms
    "artificial intelligence",
    "machine learning",
    "deep learning",
    "neural network",
    "neural networks",
    "nlp",
    "natural language processing",
    "computer vision",
    "reinforcement learning",
    "generative ai",
    "gen ai",
    "genai",
    "foundation model",
    "foundation models",
    "multimodal",
    "self supervised learning",
    "self-supervised learning",

    # Shorthand terms (important for title-only matching)
    "ai",
    "ml",
    "ai/ml",
    "ml/ai",
    "dl",
    "cv",  # computer vision

    # Models & architectures
    "large language model",
    "large language models",
    "llm",
    "llms",
    "gpt",
    "gpt-4",
    "gpt-5",
    "bert",
    "t5",
    "llama",
    "mistral",
    "claude",
    "gemini",
    "transformer",
    "transformers",
    "attention mechanism",
    "diffusion model",
    "diffusion models",
    "stable diffusion",
    "midjourney",
    "dall-e",
    "gan",
    "gans",
    "generative adversarial network",
    "convolutional neural network",
    "cnn",
    "rnn",
    "lstm",
    "gru",
    "vae",
    "autoencoder",

    # ML techniques
    "supervised learning",
    "unsupervised learning",
    "semi supervised learning",
    "transfer learning",
    "fine tuning",
    "fine-tuning",
    "finetuning",
    "post-training",
    "post training",
    "pretraining",
    "pre-training",
    "rlhf",
    "hyperparameter tuning",
    "feature engineering",
    "model training",
    "model evaluation",
    "model deployment",
    "model serving",
    "model monitoring",
    "model optimization",
    "experiment tracking",
    "ablation",

    # Libraries & frameworks
    "tensorflow",
    "pytorch",
    "torch",
    "keras",
    "scikit-learn",
    "sklearn",
    "hugging face",
    "huggingface",
    "transformers",
    "langchain",
    "llamaindex",
    "llama-index",
    "ray",
    "mlflow",
    "onnx",
    "fastai",
    "jax",
    "flax",
    "triton",
    "tensorrt",
    "vllm",
    "tgi",
    "deepspeed",
    "megatron",
    "nemo",
    "paddlepaddle",
    "mxnet",
    "caffe",

    # LLM / GenAI tooling
    "prompt engineering",
    "prompt engineer",
    "rag",
    "retrieval augmented generation",
    "retrieval-augmented",
    "vector database",
    "vector db",
    "vector search",
    "embeddings",
    "embedding",
    "semantic search",
    "faiss",
    "pinecone",
    "weaviate",
    "chroma",
    "milvus",
    "qdrant",
    "agents",
    "agentic",
    "tool use",
    "function calling",

    # Providers & platforms
    "openai",
    "anthropic",
    "cohere",
    "azure openai",
    "aws sagemaker",
    "sagemaker",
    "google vertex ai",
    "vertex ai",
    "bedrock",
    "replicate",
    "together ai",
    "anyscale",
    "modal",
    "runpod",
    "lambda labs",

    # Data science & analytics
    "data science",
    "data scientist",
    "predictive analytics",
    "predictive modeling",
    "statistical modeling",
    "time series forecasting",
    "time series",
    "forecasting",
    "anomaly detection",
    "recommendation system",
    "recommendation engine",
    "recommender",
    "personalization",

    # NLP / Vision tasks
    "sentiment analysis",
    "text classification",
    "named entity recognition",
    "ner",
    "topic modeling",
    "speech recognition",
    "speech to text",
    "text to speech",
    "asr",
    "tts",
    "object detection",
    "image recognition",
    "image classification",
    "image segmentation",
    "semantic segmentation",
    "ocr",
    "document ai",
    "document understanding",

    # ML roles & job titles
    "ml engineer",
    "machine learning engineer",
    "ai engineer",
    "mlops",
    "ml ops",
    "aiops",
    "ai ops",
    "llmops",
    "ai researcher",
    "ml researcher",
    "ai specialist",
    "applied scientist",
    "research scientist",
    "research engineer",
    "computer vision engineer",
    "nlp engineer",
    "data architect",
    "ml architect",
    "ai architect",
    "ml scientist",
    "ai scientist",

    # Ops & infra
    "ml pipeline",
    "ml pipelines",
    "training pipeline",
    "inference pipeline",
    "model registry",
    "feature store",
    "distributed training",
    "model parallelism",
    "data parallelism",
    "tensor parallelism",
    "pipeline parallelism",
    "gpu",
    "gpus",
    "cuda",
    "tpu",
    "inference",
    "batch inference",
    "real-time inference",
    "serving infrastructure",

    # HPC / Performance (AI context)
    "hpc",
    "high performance computing",
    "accelerated computing",
    "gpu cluster",
    "gpu clusters",
])

# Tech stack keywords for digital presence scoring
AI_TECHSTACK_KEYWORDS = frozenset([
    # Cloud AI platforms
    "aws sagemaker",
    "azure ml",
    "google vertex ai",
    "databricks",
    "snowflake",
    "bigquery",
    "redshift",

    # ML infrastructure
    "kubernetes",
    "docker",
    "mlflow",
    "kubeflow",
    "airflow",
    "prefect",
    "dagster",

    # Data tools
    "spark",
    "pyspark",
    "hadoop",
    "kafka",
    "flink",
    "dbt",
    "fivetran",
    "airbyte",

    # Programming languages
    "python",
    "r programming",
    "julia",
    "scala",

    # Databases
    "postgresql",
    "mongodb",
    "elasticsearch",
    "redis",
    "neo4j",
    "pinecone",
    "weaviate",
    "milvus",

    # Visualization
    "tableau",
    "power bi",
    "looker",
    "metabase",

    # Version control / MLOps
    "git",
    "github",
    "gitlab",
    "dvc",
    "wandb",
    "neptune",

    # AI-specific infra
    "gpu cluster",
    "nvidia",
    "cuda",
    "ray",
    "dask",
])

# Leadership background keywords for DEF 14A parsing
AI_LEADERSHIP_KEYWORDS = frozenset([
    # Titles
    "chief data officer",
    "cdo",
    "chief analytics officer",
    "chief ai officer",
    "caio",
    "chief technology officer",
    "cto",
    "vp of data",
    "vp of ai",
    "vp of engineering",
    "head of data science",
    "head of ai",
    "head of ml",
    "data science background",
    "ai experience",
    "machine learning",
    "phd in computer science",
    "stanford ai",
    "mit ai",
    "google ai",
    "meta ai",
    "deepmind",
    "openai",
    "anthropic",
    "computer science degree",
    "statistics degree",
    "mathematics degree",
    "engineering degree",
])

# Patent classification keywords for PatentsView
PATENT_AI_KEYWORDS = frozenset([
    "artificial intelligence",
    "machine learning",
    "neural network",
    "deep learning",
    "natural language processing",
    "computer vision",
    "pattern recognition",
    "automated decision",
    "predictive model",
    "classification algorithm",
    "clustering algorithm",
    "recommendation engine",
    "speech recognition",
    "image processing",
    "data mining",
    "knowledge graph",
])

# Top AI tools for bonus scoring in tech stack
TOP_AI_TOOLS = frozenset([
    "tensorflow",
    "pytorch",
    "kubernetes",
    "spark",
    "databricks",
    "aws sagemaker",
    "mlflow",
    "hugging face",
])
